### ISSUE TITLE
CLI should exit with non-zero code when getting aws exceptions

### ISSUE THREAD

**Issue by realstraw** [krux/hyperion#340]
Currently the following exception happens but CLI exits with code 0
```
INFO: Unable to execute HTTP request: Read timed out
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(SocketInputStream.java:152)
	at java.net.SocketInputStream.read(SocketInputStream.java:122)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:442)
	at sun.security.ssl.InputRecord.read(InputRecord.java:480)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:946)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:903)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:102)
	at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:160)
	at org.apache.http.impl.io.SocketInputBuffer.fillBuffer(SocketInputBuffer.java:84)
	at org.apache.http.impl.io.AbstractSessionInputBuffer.readLine(AbstractSessionInputBuffer.java:273)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)
	at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:283)
	at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:251)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.receiveResponseHeader(ManagedClientConnectionImpl.java:197)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:271)
	at com.amazonaws.http.protocol.SdkHttpRequestExecutor.doReceiveResponse(SdkHttpRequestExecutor.java:66)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
	at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:685)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:487)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:822)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:576)
	at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:362)
	at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:328)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:307)
	at com.amazonaws.services.datapipeline.DataPipelineClient.invoke(DataPipelineClient.java:1479)
	at com.amazonaws.services.datapipeline.DataPipelineClient.putPipelineDefinition(DataPipelineClient.java:1004)
	at com.krux.hyperion.HyperionAwsClientForPipelineDef.createPipeline(HyperionAwsClient.scala:126)
	at com.krux.hyperion.HyperionAwsClientForPipelineDef.createPipeline(HyperionAwsClient.scala:152)
	at com.krux.hyperion.cli.CreateAction$.apply(CreateAction.scala:8)
	at com.krux.hyperion.cli.AwsAction$class.apply(AwsAction.scala:10)
	at com.krux.hyperion.cli.CreateAction$.apply(CreateAction.scala:5)
	at com.krux.hyperion.cli.EntryPoint$$anonfun$run$2.apply(EntryPoint.scala:253)
	at com.krux.hyperion.cli.EntryPoint$$anonfun$run$2.apply(EntryPoint.scala:243)
	at scala.Option.map(Option.scala:145)
	at com.krux.hyperion.cli.EntryPoint.run(EntryPoint.scala:243)
	at com.krux.hyperion.HyperionCli$class.main(HyperionCli.scala:11)
```

**Comment by realstraw** [comment]
Actually, I was wrong, it does exit correctly.
