### ISSUE TITLE
InvalidRequestException is not handled in the create and upload pipeline transaction

### ISSUE THREAD

**Issue by realstraw** [krux/hyperion#467]
The following exception is thrown but the pipeline is not cleaned up

```
Exception in thread "main" com.amazonaws.services.datapipeline.model.InvalidRequestException: Web service limit exceeded: Exceeded maximum number of objects allowed per pipeline (Service: DataPipeline; Status Code: 400; Error Code: InvalidRequestException; Request ID: 96f55510-933c-11e6-ab00-9b48e5f8ec63)
	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1275)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:873)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:576)
	at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:362)
	at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:328)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:307)
	at com.amazonaws.services.datapipeline.DataPipelineClient.invoke(DataPipelineClient.java:1479)
	at com.amazonaws.services.datapipeline.DataPipelineClient.putPipelineDefinition(DataPipelineClient.java:1004)
	at com.krux.hyperion.client.UploadPipelineObjectsTrans$$anonfun$2.apply(UploadPipelineObjectsTrans.scala:45)
	at com.krux.hyperion.client.UploadPipelineObjectsTrans$$anonfun$2.apply(UploadPipelineObjectsTrans.scala:45)
	at com.krux.hyperion.client.Retry$Retryable.retry(Retry.scala:23)
	at com.krux.hyperion.client.UploadPipelineObjectsTrans.com$krux$hyperion$client$UploadPipelineObjectsTrans$$createAndUploadObjects(UploadPipelineObjectsTrans.scala:51)
	at com.krux.hyperion.client.UploadPipelineObjectsTrans$$anonfun$action$1.apply(UploadPipelineObjectsTrans.scala:79)
	at com.krux.hyperion.client.UploadPipelineObjectsTrans$$anonfun$action$1.apply(UploadPipelineObjectsTrans.scala:78)
```

**Comment by realstraw** [comment]
Re open, as the previous fix does not really work in cleaning up the pipeline that generated the exception
