### ISSUE TITLE
Workflow StackOverflow when given too many dependencies

### ISSUE THREAD

**Issue by realstraw** [krux/hyperion#526]
E.g. the following code 

```scala
    implicit val hc: HyperionContext = new HyperionContext(ConfigFactory.load("example"))

    val ec2 = Ec2Resource()

    "not run out of memory when given long dependencies" in {
      val result = (1 to 1000).map(i => ShellCommandActivity(s"run act$i")(ec2))
        .foldLeft[WorkflowExpression](WorkflowNoActivityExpression)(_ ~> _)
        .toActivities

      println(result)
    }
```

Gives the following error:

```
[info] Exception encountered when attempting to run a suite with class name: com.krux.hyperion.workflow.WorkflowExpressionSpec *** ABORTED ***
[info]   java.lang.StackOverflowError:
[info]   at com.krux.hyperion.common.RandomizedObjectId.toString(PipelineObjectId.scala:56)
[info]   at java.lang.String.valueOf(String.java:2994)
[info]   at scala.collection.mutable.StringBuilder.append(StringBuilder.scala:200)
[info]   at scala.collection.TraversableOnce$$anonfun$addString$1.apply(TraversableOnce.scala:359)
[info]   at scala.collection.Iterator$class.foreach(Iterator.scala:891)
[info]   at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
[info]   at scala.collection.TraversableOnce$class.addString(TraversableOnce.scala:357)
[info]   at scala.collection.AbstractIterator.addString(Iterator.scala:1334)
[info]   at scala.collection.TraversableOnce$class.mkString(TraversableOnce.scala:323)
[info]   at scala.collection.AbstractIterator.mkString(Iterator.scala:1334)
```

**Comment by realstraw** [comment]
The problem is this https://github.com/krux/hyperion/blob/master/core/src/main/scala/com/krux/hyperion/workflow/WorkflowGraph.scala#L100-L123

**Comment by realstraw** [comment]
It's actually the `println(result)` that's causing the error.
